// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---------- //
// picowi_pio //
// ---------- //

#define picowi_pio_wrap_target 0
#define picowi_pio_wrap 3

#define picowi_pio_offset_stall 0u
#define picowi_pio_offset_writer 0u
#define picowi_pio_offset_reader 4u
#define picowi_pio_offset_slow_reader 15u

static const uint16_t picowi_pio_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block           side 0     
    0xa042, //  1: nop                    side 0     
    0x6001, //  2: out    pins, 1         side 0     
    0x10e1, //  3: jmp    !osre, 1        side 1     
            //     .wrap
    0x80a0, //  4: pull   block           side 0     
    0x6020, //  5: out    x, 32           side 0     
    0xe047, //  6: set    y, 7            side 0     
    0xb042, //  7: nop                    side 1     
    0xb042, //  8: nop                    side 1     
    0xb042, //  9: nop                    side 1     
    0x4001, // 10: in     pins, 1         side 0     
    0x0087, // 11: jmp    y--, 7          side 0     
    0x8020, // 12: push   block           side 0     
    0x0046, // 13: jmp    x--, 6          side 0     
    0x0004, // 14: jmp    4               side 0     
    0x80a0, // 15: pull   block           side 0     
    0x6020, // 16: out    x, 32           side 0     
    0xe047, // 17: set    y, 7            side 0     
    0xa042, // 18: nop                    side 0     
    0x4001, // 19: in     pins, 1         side 0     
    0xb042, // 20: nop                    side 1     
    0x1092, // 21: jmp    y--, 18         side 1     
    0x8020, // 22: push   block           side 0     
    0x0051, // 23: jmp    x--, 17         side 0     
    0x000f, // 24: jmp    15              side 0     
};

#if !PICO_NO_HARDWARE
static const struct pio_program picowi_pio_program = {
    .instructions = picowi_pio_program_instructions,
    .length = 25,
    .origin = 0,
};

static inline pio_sm_config picowi_pio_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + picowi_pio_wrap_target, offset + picowi_pio_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}
#endif

